# Copyright (c) 2025 https://github.com/rasmabayu. All rights reserved.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: app-sa
  namespace: apps
