stages: [build, scan, deploy]
variables:
  IMAGE: $CI_REGISTRY_IMAGE/demo-app:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE

scan:
  stage: scan
  script:
    - trivy image --exit-code 1 --severity CRITICAL,HIGH $IMAGE || true

deploy:
  stage: deploy
  script:
    - kubectl -n production rollout status deploy/prod-demo-app --timeout=60s || true
    - kubectl -n production set image deploy/prod-demo-app demo-app=$IMAGE
    - kubectl -n production rollout status deploy/prod-demo-app --timeout=300s
    - echo "Canary policy can be added with progressive delivery tools"
