# Copyright (c) 2025 https://github.com/rasmabayu. All rights reserved.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  labels: { app: filebeat }
spec:
  selector:
    matchLabels: { app: filebeat }
  template:
    metadata:
      labels: { app: filebeat }
    spec:
      serviceAccountName: filebeat
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.10.0
        args: ["-e"]
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
