# Copyright (c) 2025 https://github.com/rasmabayu. All rights reserved.
# Minimal Helm values untuk Elasticsearch (single node dev)
replicas: 1
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
resources:
  requests:
    memory: 1Gi
    cpu: 500m
