# Copyright (c) 2025 https://github.com/rasmabayu. All rights reserved.
# Minimal Helm values untuk Kibana
replicas: 1
elasticsearchHosts: "http://elasticsearch-master:9200"
resources:
  requests:
    memory: 512Mi
    cpu: 250m
