# Copyright (c) 2025 https://github.com/rasmabayu. All rights reserved.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-root
spec:
  project: default
  source:
    repoURL: https://github.com/rasmabayu/ultimate-devops-portfolio
    path: k8s-gitops/overlays/production
    targetRevision: HEAD
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
