apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  schedule: "0 2 * * *" # tiap jam 02:00
  template:
    ttl: 720h # 30 hari
    includedNamespaces:
      - apps
    storageLocation: default
    includedResources:
      - deployments
      - services
      - configmaps
      - secrets
      - persistentvolumeclaims
