# Copyright (c) 2025 https://github.com/rasmabayu. All rights reserved.
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  selector: { app: demo-app }
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
