# Copyright (c) 2025 https://github.com/rasmabayu. All rights reserved.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  endpoints:
    - port: http
      interval: 15s
